name: libvni
on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  version:
    name: Detect version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      vniversion: ${{ steps.version.outputs.vniversion }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: |
          VERSION_MAJOR=$(grep -Eo "VNI_VERSION_MAJOR\s+[0-9]+" src/vni-version.h | grep -Eo "[0-9]+")
          VERSION_MINOR=$(grep -Eo "VNI_VERSION_MINOR\s+[0-9]+" src/vni-version.h | grep -Eo "[0-9]+")
          VERSION_PATCH=$(grep -Eo "VNI_VERSION_PATCH\s+[0-9]+" src/vni-version.h | grep -Eo "[0-9]+")
          VNI_VERSION="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}"
          TAG="${VNI_VERSION}"
          echo "${TAG}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "vniversion=${VNI_VERSION}" >> $GITHUB_OUTPUT
      - name: Check git tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          GIT_TAG="${GITHUB_REF#refs/tags/}"
          EXPECTED_TAG="v${{ steps.version.outputs.tag }}"
          if [[ "${GIT_TAG}" != "${EXPECTED_TAG}" ]]; then
            echo "Error: Git tag (${GIT_TAG}) does not match version from vni-version.h (v${{ steps.version.outputs.tag }})"
            exit 1
          fi

  build:
    name: Build libvni-${{ matrix.platform }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    needs: [ version ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x64
          - os: windows-latest
            platform: win
            arch: x86
          - os: macos-latest
            platform: macos
            arch: arm64
          - os: macos-latest
            platform: macos
            arch: x64
          - os: ubuntu-24.04
            platform: linux
            arch: x64
          - os: ubuntu-24.04-arm
            platform: linux
            arch: aarch64
          - os: ubuntu-24.04
            platform: android
            arch: arm64-v8a
          - os: macos-latest
            platform: ios
            arch: arm64
          - os: macos-latest
            platform: ios-simulator
            arch: arm64
          - os: macos-latest
            platform: tvos
            arch: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build libvni-${{ matrix.platform }}-${{ matrix.arch }}
        run: |
          if [[ "${{ matrix.platform }}" == "win" ]]; then
             if [[ "${{ matrix.arch }}" == "x86" ]]; then
                cmake -G "Visual Studio 17 2022" -A Win32 -DPLATFORM=${{ matrix.platform }} -DARCH=${{ matrix.arch }} -B build
             else
                cmake -G "Visual Studio 17 2022" -DPLATFORM=${{ matrix.platform }} -DARCH=${{ matrix.arch }} -B build
             fi
             cmake --build build --config Release
          else
             if [[ "$(uname)" == "Darwin" ]]; then
                NUM_PROCS=$(sysctl -n hw.ncpu)
             else
                NUM_PROCS=$(nproc)
             fi
             cmake -DCMAKE_BUILD_TYPE=Release -DPLATFORM=${{ matrix.platform }} -DARCH=${{ matrix.arch }} -B build
             cmake --build build -- -j${NUM_PROCS}
          fi
      - name: Prepare artifacts
        id: artifacts
        run: |
          mkdir tmp
          if [[ "${{ matrix.platform }}" == "win" ]]; then
             ARTIFACT_PATH="tmp"
             if [[ "${{ matrix.arch }}" == "x86" ]]; then
                cp build/Release/vni.lib tmp
                cp build/Release/vni.dll tmp
             else
                cp build/Release/vni64.lib tmp
                cp build/Release/vni64.dll tmp
             fi
             cp build/Release/vni_static.lib tmp
          else
            ARTIFACT_PATH="libvni-${{ needs.version.outputs.tag }}-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz"
            if [[ "${{ matrix.platform }}" == "macos" ]]; then
               cp build/libvni.a tmp
               cp build/libvni.*.dylib tmp
            elif [[ "${{ matrix.platform }}" == "linux" ]]; then
               cp build/libvni.a tmp
               cp build/libvni.so.* tmp
            elif [[ "${{ matrix.platform }}" == "ios" || "${{ matrix.platform }}" == "ios-simulator" || "${{ matrix.platform }}" == "tvos" ]]; then
               cp build/libvni.a tmp
               cp build/libvni.*.dylib tmp
            elif [[ "${{ matrix.platform }}" == "android" ]]; then
               cp build/libvni.a tmp
               cp build/libvni.so tmp
            fi
            cd tmp
            tar -czvf ../${ARTIFACT_PATH} *
          fi
          echo "artifact_path=${ARTIFACT_PATH}" >> $GITHUB_OUTPUT
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libvni-${{ needs.version.outputs.tag }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: ${{ steps.artifacts.outputs.artifact_path }}

  post-build:
    runs-on: macos-latest
    needs: [ version, build ]
    name: Build libvni-macos
    steps:
      - uses: actions/download-artifact@v4
      - name: Unpack artifacts
        run: |
          cd libvni-${{ needs.version.outputs.tag }}-macos-x64
          tar -xzvf libvni-${{ needs.version.outputs.tag }}-macos-x64.tar.gz
          cd ..
          cd libvni-${{ needs.version.outputs.tag }}-macos-arm64
          tar -xzvf libvni-${{ needs.version.outputs.tag }}-macos-arm64.tar.gz
      - name: Combine macos architectures
        run: |
          mkdir tmp
          lipo -create -output tmp/libvni-${{ needs.version.outputs.tag }}.dylib \
             libvni-${{ needs.version.outputs.tag }}-macos-arm64/libvni.${{ needs.version.outputs.vniversion }}.dylib \
             libvni-${{ needs.version.outputs.tag }}-macos-x64/libvni.${{ needs.version.outputs.vniversion }}.dylib
      - name: Prepare artifacts
        run: |
          cd tmp
          tar -czvf ../libvni-${{ needs.version.outputs.tag }}-macos.tar.gz *
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libvni-${{ needs.version.outputs.tag }}-macos
          path: libvni-${{ needs.version.outputs.tag }}-macos.tar.gz
      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          zip -r libvni-${{ needs.version.outputs.tag }}-win-x64.zip libvni-${{ needs.version.outputs.tag }}-win-x64
          zip -r libvni-${{ needs.version.outputs.tag }}-win-x86.zip libvni-${{ needs.version.outputs.tag }}-win-x86
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            libvni-${{ needs.version.outputs.tag }}-win-x64.zip
            libvni-${{ needs.version.outputs.tag }}-win-x86.zip
            libvni-${{ needs.version.outputs.tag }}-macos-arm64/libvni-${{ needs.version.outputs.tag }}-macos-arm64.tar.gz
            libvni-${{ needs.version.outputs.tag }}-macos-x64/libvni-${{ needs.version.outputs.tag }}-macos-x64.tar.gz
            libvni-${{ needs.version.outputs.tag }}-macos.tar.gz
            libvni-${{ needs.version.outputs.tag }}-linux-x64/libvni-${{ needs.version.outputs.tag }}-linux-x64.tar.gz
            libvni-${{ needs.version.outputs.tag }}-linux-aarch64/libvni-${{ needs.version.outputs.tag }}-linux-aarch64.tar.gz
            libvni-${{ needs.version.outputs.tag }}-ios-arm64/libvni-${{ needs.version.outputs.tag }}-ios-arm64.tar.gz
            libvni-${{ needs.version.outputs.tag }}-ios-simulator-arm64/libvni-${{ needs.version.outputs.tag }}-ios-simulator-arm64.tar.gz
            libvni-${{ needs.version.outputs.tag }}-tvos-arm64/libvni-${{ needs.version.outputs.tag }}-tvos-arm64.tar.gz
            libvni-${{ needs.version.outputs.tag }}-android-arm64-v8a/libvni-${{ needs.version.outputs.tag }}-android-arm64-v8a.tar.gz
